name: Test Report
on:
  workflow_run:
    workflows:
      - .NET
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Xunit Tests
        path: test-results.trx
        reporter: dotnet-trx
