name: Test Report
on:
  workflow_run:
    workflows:
      - .NET
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: Xunit Tests                # Name of the check run which will be created
        path: '*.dll'                     # Path to test results (inside artifact .zip)
        reporter: dotnet-trx              # Format of test results
